### ISSUE TITLE
Eventual crash on HoloLens from GamepadXRInputSource

### ISSUE THREAD

**Issue by speigg** [immersive-web/webxr-polyfill#153]
```js
Unable to get property '0' of undefined or null reference
TypeError: Unable to get property '0' of undefined or null reference
   at fromRotationTranslation (https://cdn.jsdelivr.net/npm/webxr-polyfill@latest/build/webxr-polyfill.js:301:3)
   at GamepadXRInputSource.prototype.updateBasePoseMatrix (https://cdn.jsdelivr.net/npm/webxr-polyfill@latest/build/webxr-polyfill.js:5541:7)
   at GamepadXRInputSource.prototype.getXRPose (https://cdn.jsdelivr.net/npm/webxr-polyfill@latest/build/webxr-polyfill.js:5548:5)
   at WebVRDevice.prototype.getInputPose (https://cdn.jsdelivr.net/npm/webxr-polyfill@latest/build/webxr-polyfill.js:5897:9)
   at XRFrame.prototype.getPose (https://cdn.jsdelivr.net/npm/webxr-polyfill@latest/build/webxr-polyfill.js:1295:7)
   at update (https://10.0.0.72:1234/index.4ca7163e.js:17013:11)
   at onAnimationFrame (https://10.0.0.72:1234/index.4ca7163e.js:17380:7)
   at onAnimationFrame (https://10.0.0.72:1234/index.4ca7163e.js:10529:5)
   at Anonymous function[PRIVATE$15].onDeviceFrame (https://cdn.jsdelivr.net/npm/webxr-polyfill@latest/build/webxr-polyfill.js:1465:7)
```

Note, I had to inject a DOMPointReadOnly polyfill in order to run on HoloLens(2) (including the static "fromPoint" function which is missing from the DOMPointReadOnly polypill in this repo).

**Comment by speigg** [comment]
It appears that this actually comes back to the DOMPointReadOnly not being implemented correctly, specifically the constructor parameter handling.

**Comment by speigg** [comment]
The problem seems to be that `GamepadXRInputSource.prototype.updateBasePoseMatrix()` assumes that the gamepad's pose orientation will always be available when position is available.
